version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    restart: "unless-stopped"
    environment: 
      - PORT=${PORT}
    networks: 
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytdlapi.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.ytdlapi.entrypoints=websecure
      - traefik.http.routers.ytdlapi.tls=true
      - traefik.http.routers.ytdlapi.tls.certresolver=le
      - traefik.http.services.ytdlapi.loadbalancer.server.port=${PORT}
 
networks:
  proxy:
    external: true